# Generated by Django 2.2.2 on 2019-08-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190827_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
