# Generated by Django 2.2.2 on 2019-10-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LastName',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
