# Generated by Django 2.2.2 on 2019-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.CharField(choices=[('billing', 'billing'), ('shipping', 'shipping')], max_length=120),
        ),
    ]
