# Generated by Django 2.2.2 on 2019-08-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190813_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripition',
            new_name='description',
        ),
    ]
