# Generated by Django 2.2.2 on 2019-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
